### ISSUE TITLE
In the Instantons.sage file, the qde function has two bugs

### ISSUE THREAD

**Issue by jrayers97** [liu-henry-hl/boxcounting#1]
In the instantons.sage file the qde function has two errors which cause it to fail to run: The qde_wall function which is called only has three inputs, instead of the required 4. This is due to the q*z being applied, which I think should be a q,z. Second the O(1) function being called should be O(1,n) to specify the matrix size.

**Comment by liu-henry-hl** [comment]
Thanks! Fixed
